spring:
  application:
    name: monkey-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monkey_db
    username: root
    password: 66666666
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 这段配置仅在测试时发挥作用 实际的接口调用中 是根据当前登陆的用户来获得ak / sk 并初始化客户端的
monkey:
  client:
    access-key: yupi
    secret-key: abcdefg
dubbo:
  application:
    qosPort: 11100
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 11110
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
